capacity: 100000
energy_per_tick: 75
electric_blast_furnace_time: 300
speed: 1

multiblock_json: '{
   "structure":[
      [
         "sss",
         "sss",
         "sss",
         "*c*"
      ],
      [
         "sss",
         "s*s",
         "sss",
         "***"
      ],
      [
         "sss",
         "s*s",
         "sss",
         "***"
      ],
      [
         "sss",
         "sss",
         "sss",
         "***"
      ]
   ],
   "mapping":{
      "c":"machines:electric_blast_furnace",
      "s":"machines:standard_machine_casing",
      " ":"minecraft:air"
   }
}'