capacity: 100000
energy_per_tick: 75
electric_blast_furnace_time: 300
speed: 1

multiblock_json: '{
   "structure":[
      [
         "mmm",
         "mmm",
         "mmm",
         "*c*"
      ],
      [
         "mmm",
         "mlm",
         "mmm",
         "***"
      ],
      [
         "mmm",
         "mlm",
         "mmm",
         "***"
      ],
      [
         "mmm",
         "mmm",
         "mmm",
         "***"
      ]
   ],
   "mapping":{
      "c":"machines:electric_blast_furnace",
      "m":["machines:standard_machine_casing", "machines:reinforced_machine_casing", "machines:advanced_machine_casing"],
      "l":["minecraft:air", "minecraft:lava"],
      " ":"minecraft:air"
   }
}'