capacity: 100000
energy_per_tick: 128
smelting_time: 120
speed: 1

# Multiblock structure configuration
multiblock:
  # The structure is behind the controller
  facing: "back"

  # Pattern definition - defines a 3x4x3 structure (width x height x depth)
  # When facing="back", the layers are defined as depth slices going away from the controller
  # Each 2D grid is width x height (3x4)
  pattern:
    # Controller layer
    - - ""
      - ""
      - ""
      - "?c?"
    # First layer (closest to controller)
    - - "xxx"
      - "xxx"
      - "xxx"
      - "xxx"
    # Second layer (middle)
    - - "xxx"
      - "x x"
      - "x x"
      - "xxx"
    # Third layer (furthest from controller)
    - - "xxx"
      - "xxx"
      - "xxx"
      - "xxx"

  # Block definitions for pattern letters
  blocks:
    x: "gregtech:machine_casing_heat_proof"  # Heat proof casing
    " ": "minecraft:air"                     # Air space inside

  # Relative position of the structure to the controller
  # When facing="back", this positions the structure behind the controller
  position: [-1, -1, 1]